-- MySQL Script generated by MySQL Workbench
-- Mon May 31 19:43:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mkt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mkt` ;

-- -----------------------------------------------------
-- Schema mkt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mkt` DEFAULT CHARACTER SET utf8 ;
USE `mkt` ;

-- -----------------------------------------------------
-- Table `mkt`.`perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkt`.`perguntas` ;

CREATE TABLE IF NOT EXISTS `mkt`.`perguntas` (
  `idperguntas` INT NOT NULL,
  `pergunta` VARCHAR(200) NOT NULL,
  `resposta1` VARCHAR(200) NOT NULL,
  `resposta2` VARCHAR(200) NOT NULL,
  `resposta3` VARCHAR(200) NOT NULL,
  `fase`varchar(45),
  PRIMARY KEY (`idperguntas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
